### ISSUE TITLE
Wrong path in README.

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry-community/shell-boshrelease#1]
In [README](https://github.com/cloudfoundry-community/shell-boshrelease/blob/master/README.md)
bosh upload release releases/shell-1.yml
Should be
bosh upload release releases/shell/shell-1.yml

**Comment by jhunt** [comment]
Thanks!  I think this might be an issue in bosh-gen, so I will also submit a PR to that project, to stop this from being a problem with other releases, in the future.
